package usc.edu.sql.fpa.utils;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class APIsConstants {

    public static List<String> Basic_Listeners = Arrays.asList(
            "OnClickListener","OnDragListener","OnFocusChangeListener","OnGenericMotionListener","OnHoverListener","OnKeyListener","OnLongClickListener" ,"OnTouchListener"
    );

    public static List<String> Service_Senders = Arrays.asList(
            "void stopSelf()", "void stopSelf(int)", "boolean stopSelfResult(int)",
            "android.content.ComponentName startService(android.content.Intent)",
            "boolean stopService(android.content.Intent)",
            "boolean bindService(android.content.Intent,android.content.ServiceConnection,int)",
            "boolean bindIsolatedService(android.content.Intent,int,String,java.util.concurrent.Executor,android.content.ServiceConnection)",
            "void unbindService(android.content.ServiceConnection)");

    public static List<String> BroadcastReceiver_Senders = Arrays.asList(
            "android.os.IBinder peekService(android.content.Context,android.content.Intent)",
            "void sendBroadcast(android.content.Intent)",
            "void sendBroadcast(android.content.Intent,java.lang.String)",
            "void sendOrderedBroadcast(android.content.Intent,java.lang.String)",
            "void sendOrderedBroadcast(android.content.Intent,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
            "void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String)",
            "void sendOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void sendStickyBroadcast(android.content.Intent)",
            "void sendStickyOrderedBroadcast(android.content.Intent,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void sendStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
            "void sendStickyOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void removeStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)");

    public static List<String> Activity_Senders = Arrays.asList(
            "void startActivityForResult(android.content.Intent,int)",
            "void startActivityForResult(android.content.Intent,int,android.os.Bundle)",
            "void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int)",
            "void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)",
            "void startActivity(android.content.Intent)",
            "void startActivity(android.content.Intent,android.os.Bundle)",
            "void startActivities(android.content.Intent[])",
            "void startActivities(android.content.Intent[],android.os.Bundle)",
            "void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int)",
            "void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int,android.os.Bundle)",
            "boolean startActivityIfNeeded(android.content.Intent,int)",
            "boolean startActivityIfNeeded(android.content.Intent,int,android.os.Bundle)",
            "boolean startNextMatchingActivity(android.content.Intent)",
            "boolean startNextMatchingActivity(android.content.Intent,android.os.Bundle)",
            "void startActivityFromChild(android.app.Activity,android.content.Intent,int)",
            "void startActivityFromChild(android.app.Activity,android.content.Intent,int,android.os.Bundle)",
            "void startActivityFromFragment(android.app.Fragment,android.content.Intent,int)",
            "void startActivityFromFragment(android.app.Fragment,android.content.Intent,int,android.os.Bundle)",
            "void startIntentSenderFromChild(android.app.Activity,android.content.IntentSender,int,android.content.Intent,int,int,int)",
            "void startIntentSenderFromChild(android.app.Activity,android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)");

    public static List<String> Service_Recievers = Arrays.asList("void onStart(android.content.Intent,int)",
            "int onStartCommand(android.content.Intent,int,int)", "android.os.IBinder onBind(android.content.Intent)",
            "void onHandleIntent(android.content.Intent)", "boolean onUnbind(android.content.Intent)",
            "void onRebind(android.content.Intent)");

    public static List<String> Activity_Recievers_APIs = Arrays.asList(
            "android.content.Intent getIntent()",
            "android.content.Intent getParentActivityIntent()");

    public static List<String> Activity_Recievers_Callbacks = Arrays.asList(
            "void onNewIntent(android.content.Intent)",
            "void onActivityResult(int,int,android.content.Intent)");

    public static List<String> BroadCastReceiver_Recievers = Arrays
            .asList("void onReceive(android.content.Context,android.content.Intent)");

    public static List<String> iccCalls = Arrays.asList("void setIntent(android.content.Intent)",
            "android.content.Intent getIntent()", "void startActivityForResult(android.content.Intent,int)",
            "void startActivityForResult(android.content.Intent,int,android.os.Bundle)",
            "void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int)",
            "void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)",
            "void startActivity(android.content.Intent)",

            "void startActivity(android.content.Intent,android.os.Bundle)",
            "void startActivities(android.content.Intent[])",
            "void startActivities(android.content.Intent[],android.os.Bundle)",
            "void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int)",
            "void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int,android.os.Bundle)",
            "boolean startActivityIfNeeded(android.content.Intent,int)",
            "boolean startActivityIfNeeded(android.content.Intent,int,android.os.Bundle)",
            "boolean startNextMatchingActivity(android.content.Intent)",
            "boolean startNextMatchingActivity(android.content.Intent,android.os.Bundle)",
            "void startActivityFromChild(android.app.Activity,android.content.Intent,int)",
            "void startActivityFromChild(android.app.Activity,android.content.Intent,int,android.os.Bundle)",
            "void startActivityFromFragment(android.app.Fragment,android.content.Intent,int)",
            "void startActivityFromFragment(android.app.Fragment,android.content.Intent,int,android.os.Bundle)",
            "void startIntentSenderFromChild(android.app.Activity,android.content.IntentSender,int,android.content.Intent,int,int,int)",
            "void startIntentSenderFromChild(android.app.Activity,android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)",
            "void sendBroadcast(android.content.Intent)", "void sendBroadcast(android.content.Intent,java.lang.String)",
            "void sendOrderedBroadcast(android.content.Intent,java.lang.String)",
            "void sendOrderedBroadcast(android.content.Intent,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
            "void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String)",
            "void sendOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void sendStickyBroadcast(android.content.Intent)",
            "void sendStickyOrderedBroadcast(android.content.Intent,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void removeStickyBroadcast(android.content.Intent)",
            "void sendStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
            "void sendStickyOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
            "void removeStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
            "android.content.Intent registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter)",
            "android.content.Intent registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter,java.lang.String,android.os.Handler)",
            "void unregisterReceiver(android.content.BroadcastReceiver)",
            "android.content.ComponentName startService(android.content.Intent)",
            "boolean stopService(android.content.Intent)",
            "boolean bindService(android.content.Intent,android.content.ServiceConnection,int)",
            "void unbindService(android.content.ServiceConnection)");

    public static List<String> intentAPIs = Arrays.asList("void <init>()", "void <init>(android.content.Intent)",
            "void <init>(java.lang.String)", "void <init>(java.lang.String,android.net.Uri)",
            "void <init>(android.content.Context,java.lang.Class)",
            "void <init>(java.lang.String,android.net.Uri,android.content.Context,java.lang.Class)",
            "android.content.Intent createChooser(android.content.Intent,java.lang.CharSequence)",
            "java.lang.Object clone()", "android.content.Intent cloneFilter()",
            "android.content.Intent makeMainActivity(android.content.ComponentName)",
            "android.content.Intent makeMainSelectorActivity(java.lang.String,java.lang.String)",
            "android.content.Intent makeRestartActivityTask(android.content.ComponentName)",
            "android.content.Intent getIntent(java.lang.String)",
            "android.content.Intent parseUri(java.lang.String,int)",
            "android.content.Intent getIntentOld(java.lang.String)", "java.lang.String getAction()",
            "android.net.Uri getData()", "java.lang.String getDataString()", "java.lang.String getScheme()",
            "java.lang.String getType()", "java.lang.String resolveType(android.content.Context)",
            "java.lang.String resolveType(android.content.ContentResolver)",
            "java.lang.String resolveTypeIfNeeded(android.content.ContentResolver)",
            "boolean hasCategory(java.lang.String)", "java.util.Set getCategories()",
            "android.content.Intent getSelector()", "android.content.ClipData getClipData()",
            "void setExtrasClassLoader(java.lang.ClassLoader)", "boolean hasExtra(java.lang.String)",
            "boolean hasFileDescriptors()", "boolean getBooleanExtra(java.lang.String,boolean)",
            "byte getByteExtra(java.lang.String,byte)", "short getShortExtra(java.lang.String,short)",
            "char getCharExtra(java.lang.String,char)", "int getIntExtra(java.lang.String,int)",
            "long getLongExtra(java.lang.String,long)", "float getFloatExtra(java.lang.String,float)",
            "double getDoubleExtra(java.lang.String,double)", "java.lang.String getStringExtra(java.lang.String)",
            "java.lang.CharSequence getCharSequenceExtra(java.lang.String)",
            "android.os.Parcelable getParcelableExtra(java.lang.String)",
            "android.os.Parcelable[] getParcelableArrayExtra(java.lang.String)",
            "java.util.ArrayList getParcelableArrayListExtra(java.lang.String)",
            "java.io.Serializable getSerializableExtra(java.lang.String)",
            "java.util.ArrayList getIntegerArrayListExtra(java.lang.String)",
            "java.util.ArrayList getStringArrayListExtra(java.lang.String)",
            "java.util.ArrayList getCharSequenceArrayListExtra(java.lang.String)",
            "boolean[] getBooleanArrayExtra(java.lang.String)", "byte[] getByteArrayExtra(java.lang.String)",
            "short[] getShortArrayExtra(java.lang.String)", "char[] getCharArrayExtra(java.lang.String)",
            "int[] getIntArrayExtra(java.lang.String)", "long[] getLongArrayExtra(java.lang.String)",
            "float[] getFloatArrayExtra(java.lang.String)", "double[] getDoubleArrayExtra(java.lang.String)",
            "java.lang.String[] getStringArrayExtra(java.lang.String)",
            "java.lang.CharSequence[] getCharSequenceArrayExtra(java.lang.String)",
            "android.os.Bundle getBundleExtra(java.lang.String)", "android.os.Bundle getExtras()", "int getFlags()",
            "java.lang.String getPackage()", "android.content.ComponentName getComponent()",
            "android.graphics.Rect getSourceBounds()",
            "android.content.ComponentName resolveActivity(android.content.pm.PackageManager)",
            "android.content.pm.ActivityInfo resolveActivityInfo(android.content.pm.PackageManager,int)",
            "android.content.Intent setAction(java.lang.String)", "android.content.Intent setData(android.net.Uri)",
            "android.content.Intent setDataAndNormalize(android.net.Uri)",
            "android.content.Intent setType(java.lang.String)",
            "android.content.Intent setTypeAndNormalize(java.lang.String)",
            "android.content.Intent setDataAndType(android.net.Uri,java.lang.String)",
            "android.content.Intent setDataAndTypeAndNormalize(android.net.Uri,java.lang.String)",
            "android.content.Intent addCategory(java.lang.String)", "void removeCategory(java.lang.String)",
            "void setSelector(android.content.Intent)", "void setClipData(android.content.ClipData)",
            "android.content.Intent putExtra(java.lang.String,boolean)",
            "android.content.Intent putExtra(java.lang.String,byte)",
            "android.content.Intent putExtra(java.lang.String,char)",
            "android.content.Intent putExtra(java.lang.String,short)",
            "android.content.Intent putExtra(java.lang.String,int)",
            "android.content.Intent putExtra(java.lang.String,long)",
            "android.content.Intent putExtra(java.lang.String,float)",
            "android.content.Intent putExtra(java.lang.String,double)",
            "android.content.Intent putExtra(java.lang.String,java.lang.String)",
            "android.content.Intent putExtra(java.lang.String,java.lang.CharSequence)",
            "android.content.Intent putExtra(java.lang.String,android.os.Parcelable)",
            "android.content.Intent putExtra(java.lang.String,android.os.Parcelable[])",
            "android.content.Intent putParcelableArrayListExtra(java.lang.String,java.util.ArrayList)",
            "android.content.Intent putIntegerArrayListExtra(java.lang.String,java.util.ArrayList)",
            "android.content.Intent putStringArrayListExtra(java.lang.String,java.util.ArrayList)",
            "android.content.Intent putCharSequenceArrayListExtra(java.lang.String,java.util.ArrayList)",
            "android.content.Intent putExtra(java.lang.String,java.io.Serializable)",
            "android.content.Intent putExtra(java.lang.String,boolean[])",
            "android.content.Intent putExtra(java.lang.String,byte[])",
            "android.content.Intent putExtra(java.lang.String,short[])",
            "android.content.Intent putExtra(java.lang.String,char[])",
            "android.content.Intent putExtra(java.lang.String,int[])",
            "android.content.Intent putExtra(java.lang.String,long[])",
            "android.content.Intent putExtra(java.lang.String,float[])",
            "android.content.Intent putExtra(java.lang.String,double[])",
            "android.content.Intent putExtra(java.lang.String,java.lang.String[])",
            "android.content.Intent putExtra(java.lang.String,java.lang.CharSequence[])",
            "android.content.Intent putExtra(java.lang.String,android.os.Bundle)",
            "android.content.Intent putExtras(android.content.Intent)",
            "android.content.Intent putExtras(android.os.Bundle)",
            "android.content.Intent replaceExtras(android.content.Intent)",
            "android.content.Intent replaceExtras(android.os.Bundle)", "void removeExtra(java.lang.String)",
            "android.content.Intent setFlags(int)", "android.content.Intent addFlags(int)",
            "android.content.Intent setPackage(java.lang.String)",
            "android.content.Intent setComponent(android.content.ComponentName)",
            "android.content.Intent setClassName(android.content.Context,java.lang.String)",
            "android.content.Intent setClassName(java.lang.String,java.lang.String)",
            "android.content.Intent setClass(android.content.Context,java.lang.Class)",
            "void setSourceBounds(android.graphics.Rect)", "int fillIn(android.content.Intent,int)",
            "boolean filterEquals(android.content.Intent)", "int filterHashCode()", "java.lang.String toString()",
            "java.lang.String toURI()", "java.lang.String toUri(int)", "int describeContents()",
            "void writeToParcel(android.os.Parcel,int)", "void readFromParcel(android.os.Parcel)",
            "android.content.Intent parseIntent(android.content.res.Resources,org.xmlpull.v1.XmlPullParser,android.util.AttributeSet)",
            "java.lang.String normalizeMimeType(java.lang.String)", "void <clinit>()"
    );


    public static List<List<String>> iccOtherApis = Arrays.asList(
            Arrays.asList("android.content.ContentResolver", "applyBatch"),
            Arrays.asList("android.content.IntentFilter$AuthorityEntry", "getHost"),
            Arrays.asList("android.app.PendingIntent", "equals"),
            Arrays.asList("android.widget.AdapterViewAnimator", "setRemoteViewsAdapter"),
            Arrays.asList("android.content.ContentResolver", "removePeriodicSync"),
            Arrays.asList("android.widget.ShareActionProvider", "setShareIntent"),
            Arrays.asList("android.widget.RemoteViews", "setIntent"),
            Arrays.asList("android.content.ContentResolver", "requestSync"),
            Arrays.asList("android.content.ContentResolver", "isSyncActive"),
            Arrays.asList("android.widget.ListView", "setRemoteViewsAdapter"),
            Arrays.asList("android.content.ContentResolver", "registerContentObserver"),
            Arrays.asList("android.content.ContentResolver", "cancelSync"),
            Arrays.asList("android.content.Intent$FilterComparison", "getIntent"),
            Arrays.asList("android.content.ContentResolver", "getSyncAdapterTypes"),
            Arrays.asList("android.content.ContentResolver", "getOutgoingPersistedUriPermissions"),
            Arrays.asList("android.content.Intent", "filterEquals"),
            Arrays.asList("android.content.ContentResolver", "getPersistedUriPermissions"),
            Arrays.asList("android.preference.Preference", "setIntent"),
            Arrays.asList("android.content.ContentResolver", "getCurrentSyncs"),
            Arrays.asList("android.content.ContentResolver", "notifyChange"),
            Arrays.asList("android.content.ContentResolver", "getMasterSyncAutomatically"),
            Arrays.asList("android.content.ContentResolver", "getCurrentSync"),
            Arrays.asList("android.app.Activity", "setIntent"),
            Arrays.asList("android.content.ContentResolver", "startSync"),
            Arrays.asList("android.content.ContentResolver", "<init>"),
            Arrays.asList("android.content.IntentSender", "writeIntentSenderOrNullToParcel"),
            Arrays.asList("android.content.ContentResolver", "validateSyncExtrasBundle"),
            Arrays.asList("android.content.ContentResolver", "unregisterContentObserver"),
            Arrays.asList("android.content.ContentResolver", "getIsSyncable"),
            Arrays.asList("android.content.IntentFilter", "writeToXml"),
            Arrays.asList("android.content.IntentFilter$AuthorityEntry", "getPort"),
            Arrays.asList("android.content.IntentFilter$AuthorityEntry", "equals"),
            Arrays.asList("android.content.ContentResolver", "setIsSyncable"),
            Arrays.asList("android.app.PendingIntent", "hashCode"),
            Arrays.asList("android.content.pm.ShortcutInfo$Builder", "setIntent"),
            Arrays.asList("android.widget.RemoteViews", "setRemoteAdapter"),
            Arrays.asList("android.content.Intent$FilterComparison", "hashCode"),
            Arrays.asList("android.content.IntentSender", "hashCode"),
            Arrays.asList("android.content.ContentResolver", "addPeriodicSync"),
            Arrays.asList("android.widget.GridView", "setRemoteViewsAdapter"),
            Arrays.asList("android.preference.Preference", "getIntent"),
            Arrays.asList("android.content.IntentSender", "equals"),
            Arrays.asList("android.content.ContentResolver", "addStatusChangeListener"),
            Arrays.asList("android.content.IntentFilter$AuthorityEntry", "<init>"),
            Arrays.asList("android.widget.AbsListView", "setRemoteViewsAdapter"),
            Arrays.asList("android.content.ContentResolver", "refresh"),
            Arrays.asList("android.content.ContentResolver", "setMasterSyncAutomatically"),
            Arrays.asList("android.content.ContentResolver", "setSyncAutomatically"),
            Arrays.asList("android.content.ContentResolver", "getPeriodicSyncs"),
            Arrays.asList("android.content.Intent$FilterComparison", "equals"),
            Arrays.asList("android.content.ContentResolver", "isSyncPending"),
            Arrays.asList("android.app.PendingIntent", "<clinit>"),
            Arrays.asList("android.widget.RemoteViews", "setPendingIntentTemplate"),
            Arrays.asList("android.content.ContentResolver", "removeStatusChangeListener"),
            Arrays.asList("android.content.IntentFilter", "writeToParcel"),
            Arrays.asList("android.content.Intent", "filterHashCode"),
            Arrays.asList("android.app.PendingIntent", "cancel"),
            Arrays.asList("android.content.ContentResolver", "getSyncAutomatically")
    );
    public static List<List<String>> iccUncertainApis = Arrays.asList(
            Arrays.asList("android.content.ClipData", "newUri"),
            Arrays.asList("android.content.ContentProviderClient", "delete"),
            Arrays.asList("android.content.Intent", "writeToParcel"),
            Arrays.asList("android.content.ContentProviderClient", "getType"),
            Arrays.asList("android.content.ContentProviderClient", "openFile"),
            Arrays.asList("android.content.ContentProviderClient", "bulkInsert"),
            Arrays.asList("android.content.ContentProviderClient", "canonicalize"),
            Arrays.asList("android.content.ContentProvider", "openTypedAssetFile"),
            Arrays.asList("android.content.IntentSender", "writeToParcel"),
            Arrays.asList("android.content.ContentProviderClient", "insert"),
            Arrays.asList("android.content.ContentProviderClient", "update"),
            Arrays.asList("android.content.ContentProvider$PipeDataWriter", "writeDataToPipe"),
            Arrays.asList("android.content.ContentProviderClient", "openAssetFile"),
            Arrays.asList("android.content.Intent", "readFromParcel"),
            Arrays.asList("android.content.ContentProvider", "canonicalize"),
            Arrays.asList("android.content.ContentProviderClient", "query"),
            Arrays.asList("android.content.ContentProviderClient", "getStreamTypes"),
            Arrays.asList("android.content.ClipData", "newRawUri"),
            Arrays.asList("android.content.ContentProvider", "openAssetFile"),
            Arrays.asList("android.content.ClipData$Item", "<init>"),
            Arrays.asList("android.content.ContentProvider", "openFileHelper"),
            Arrays.asList("android.content.ContentProviderClient", "openTypedAssetFileDescriptor"),
            Arrays.asList("android.content.ClipData", "newIntent"),
            Arrays.asList("android.content.ContentProvider", "uncanonicalize"),
            Arrays.asList("android.content.ContentProvider", "openFile"),
            Arrays.asList("android.content.ContentProvider", "openPipeHelper"),
            Arrays.asList("android.content.ContentProvider", "getStreamTypes")
    );
    public static List<List<String>> iccResolvingApis = Arrays.asList(
            Arrays.asList("android.app.admin.DevicePolicyManager", "addCrossProfileIntentFilter"),
            Arrays.asList("android.content.IntentFilter", "hasDataPath"),
            Arrays.asList("android.content.pm.PackageManager", "getActivityIcon"),
            Arrays.asList("android.content.IntentFilter", "hasDataType"),
            Arrays.asList("android.content.pm.PackageManager", "queryBroadcastReceivers"),
            Arrays.asList("android.content.pm.PackageManager", "addPreferredActivity"),
            Arrays.asList("android.content.IntentFilter", "match"),
            Arrays.asList("android.content.Intent$FilterComparison", "<init>"),
            Arrays.asList("android.content.Intent", "resolveActivityInfo"),
            Arrays.asList("android.content.pm.PackageManager", "resolveActivity"),
            Arrays.asList("android.content.IntentFilter", "hasDataAuthority"),
            Arrays.asList("android.content.pm.PackageManager", "queryIntentContentProviders"),
            Arrays.asList("android.content.IntentFilter", "matchAction"),
            Arrays.asList("android.content.Intent", "resolveActivity"),
            Arrays.asList("android.content.pm.LauncherApps", "resolveActivity"),
            Arrays.asList("android.content.pm.PackageManager", "queryIntentActivities"),
            Arrays.asList("android.content.Intent", "hasCategory"),
            Arrays.asList("android.content.IntentSender", "getTargetPackage"),
            Arrays.asList("android.content.pm.PackageManager", "queryIntentActivityOptions"),
            Arrays.asList("android.content.IntentFilter", "hasAction"),
            Arrays.asList("android.content.IntentFilter", "matchDataAuthority"),
            Arrays.asList("android.content.IntentFilter$AuthorityEntry", "match"),
            Arrays.asList("android.content.Intent", "hasExtra"),
            Arrays.asList("android.content.IntentFilter", "hasCategory"),
            Arrays.asList("android.content.pm.PackageManager", "getActivityLogo"),
            Arrays.asList("android.content.IntentFilter", "hasDataScheme"),
            Arrays.asList("android.app.admin.DevicePolicyManager", "addPersistentPreferredActivity"),
            Arrays.asList("android.content.IntentFilter", "matchData"),
            Arrays.asList("android.content.pm.PackageManager", "resolveService"),
            Arrays.asList("android.content.IntentFilter", "matchCategories"),
            Arrays.asList("android.app.admin.DevicePolicyManager", "bindDeviceAdminServiceAsUser"),
            Arrays.asList("android.content.pm.PackageManager", "getActivityBanner"),
            Arrays.asList("android.content.pm.PackageManager", "queryIntentServices"),
            Arrays.asList("android.content.IntentFilter", "hasDataSchemeSpecificPart")
    );
    public static List<List<String>> iccConstructingApis = Arrays.asList(
            Arrays.asList("android.content.ContentUris", "withAppendedId"),
            Arrays.asList("android.net.Uri.Builder", "path"),
            Arrays.asList("android.accounts.AccountManager", "newChooseAccountIntent"),
            Arrays.asList("android.content.IntentFilter", "setPriority"),
            Arrays.asList("android.app.admin.DevicePolicyManager", "createAdminSupportIntent"),
            Arrays.asList("android.telecom.TelecomManager", "createManageBlockedNumbersIntent"),
            Arrays.asList("android.app.RemoteInput", "addResultsToIntent"),
            Arrays.asList("android.content.Intent", "removeFlags"),
            Arrays.asList("android.media.projection.MediaProjectionManager", "createScreenCaptureIntent"),
            Arrays.asList("android.content.Intent", "putCharSequenceArrayListExtra"),
            Arrays.asList("android.app.PendingIntent", "getService"),
            Arrays.asList("android.service.voice.AlwaysOnHotwordDetector", "createUnEnrollIntent"),
            Arrays.asList("android.net.Uri.Builder", "scheme"),
            Arrays.asList("android.app.PendingIntent", "<init>"),
            Arrays.asList("android.net.Uri.Builder", "appendEncodedPath"),
            Arrays.asList("android.net.Uri.Builder", "appendQueryParameter"),
            Arrays.asList("android.net.Uri.Builder", "encodedFragment"),
            Arrays.asList("android.net.Uri.Builder", "encodedQuery"),
            Arrays.asList("android.content.Intent", "parseUri"),
            Arrays.asList("android.content.Intent", "fillIn"),
            Arrays.asList("android.content.ContentResolver", "releasePersistableUriPermission"),
            Arrays.asList("android.content.Intent", "removeCategory"),
            Arrays.asList("android.content.Intent", "putIntegerArrayListExtra"),
            Arrays.asList("android.net.Uri.Builder", "appendPath"),
            Arrays.asList("android.app.TaskStackBuilder", "getPendingIntent"),
            Arrays.asList("android.media.session.MediaController", "getSessionActivity"),
            Arrays.asList("android.content.pm.PackageManager", "getLaunchIntentForPackage"),
            Arrays.asList("android.content.Intent", "setSelector"),
            Arrays.asList("android.net.Uri.Builder", "authority"),
            Arrays.asList("android.content.Intent", "setFlags"),
            Arrays.asList("android.content.ContentResolver", "takePersistableUriPermission"),
            Arrays.asList("android.content.Intent", "setClassName"),
            Arrays.asList("android.content.Intent", "replaceExtras"),
            Arrays.asList("android.webkit.WebChromeClient$FileChooserParams", "createIntent"),
            Arrays.asList("android.content.Intent", "addFlags"),
            Arrays.asList("android.app.KeyguardManager", "createConfirmDeviceCredentialIntent"),
            Arrays.asList("android.app.PendingIntent", "readPendingIntentOrNullFromParcel"),
            Arrays.asList("android.content.Intent", "createChooser"),
            Arrays.asList("android.content.Intent", "setDataAndTypeAndNormalize"),
            Arrays.asList("android.net.Uri.Builder", "encodedPath"),
            Arrays.asList("android.net.Uri", "fromParts"),
            Arrays.asList("android.content.IntentSender", "<init>"),
            Arrays.asList("android.os.UserManager", "createUserCreationIntent"),
            Arrays.asList("android.content.Intent", "clone"),
            Arrays.asList("android.media.tv.TvInputInfo", "createSettingsIntent"),
            Arrays.asList("android.net.Uri", "parse"),
            Arrays.asList("android.content.Intent", "setExtrasClassLoader"),
            Arrays.asList("android.content.Intent", "<init>"),
            Arrays.asList("android.content.Intent", "parseIntent"),
            Arrays.asList("android.content.Intent", "cloneFilter"),
            Arrays.asList("android.media.tv.TvInputInfo", "createSetupIntent"),
            Arrays.asList("android.net.Uri.Builder", "opaquePart"),
            Arrays.asList("android.content.Intent", "setType"),
            Arrays.asList("android.content.Intent", "getIntent"),
            Arrays.asList("android.content.Intent", "setClass"),
            Arrays.asList("android.content.Intent", "addCategory"),
            Arrays.asList("android.app.WallpaperManager", "getCropAndSetWallpaperIntent"),
            Arrays.asList("android.content.RestrictionsManager", "createLocalApprovalIntent"),
            Arrays.asList("android.app.RemoteInput", "addDataResultToIntent"),
            Arrays.asList("android.app.ActivityManager", "getRunningServiceControlPanel"),
            Arrays.asList("android.net.Uri.Builder", "encodedOpaquePart"),
            Arrays.asList("android.content.Intent", "setData"),
            Arrays.asList("android.content.Intent", "setClipData"),
            Arrays.asList("android.content.Intent", "putParcelableArrayListExtra"),
            Arrays.asList("android.content.Intent", "setComponent"),
            Arrays.asList("android.content.Intent", "putExtras"),
            Arrays.asList("android.content.ContentResolver", "canonicalize"),
            Arrays.asList("android.content.ContentValues", "*"),
            Arrays.asList("android.net.Uri.Builder", "clearQuery"),
            Arrays.asList("android.content.IntentFilter", "readFromXml"),
            Arrays.asList("android.net.Uri.Builder", "encodedAuthority"),
            Arrays.asList("android.content.Intent", "normalizeMimeType"),
            Arrays.asList("android.content.Intent", "setAction"),
            Arrays.asList("android.content.pm.PackageManager", "getLeanbackLaunchIntentForPackage"),
            Arrays.asList("android.content.IntentSender", "readIntentSenderOrNullFromParcel"),
            Arrays.asList("android.app.PendingIntent", "getActivity"),
            Arrays.asList("android.content.Intent", "setTypeAndNormalize"),
            Arrays.asList("android.content.Intent", "setDataAndNormalize"),
            Arrays.asList("android.app.PendingIntent", "getBroadcast"),
            Arrays.asList("android.net.Uri", "fromFile"),
            Arrays.asList("android.app.PendingIntent", "getForegroundService"),
            Arrays.asList("android.service.voice.AlwaysOnHotwordDetector", "createReEnrollIntent"),
            Arrays.asList("android.content.pm.PackageInstaller$SessionInfo", "createDetailsIntent"),
            Arrays.asList("android.content.ContentProviderClient", "uncanonicalize"),
            Arrays.asList("android.preference.PreferenceActivity", "onBuildStartFragmentIntent"),
            Arrays.asList("android.content.ContentResolver", "uncanonicalize"),
            Arrays.asList("android.app.PendingIntent", "getActivities"),
            Arrays.asList("android.content.Intent", "putStringArrayListExtra"),
            Arrays.asList("android.os.storage.StorageVolume", "createAccessIntent"),
            Arrays.asList("android.content.Intent", "setDataAndType"),
            Arrays.asList("android.content.Intent", "setPackage"),
            Arrays.asList("android.app.Activity", "createPendingResult"),
            Arrays.asList("android.content.Intent", "setSourceBounds"),
            Arrays.asList("android.content.Intent", "removeExtra"),
            Arrays.asList("android.content.pm.ShortcutManager", "createShortcutResultIntent"),
            Arrays.asList("android.content.Intent", "makeMainActivity"),
            Arrays.asList("android.service.voice.AlwaysOnHotwordDetector", "createEnrollIntent"),
            Arrays.asList("android.content.Intent", "makeMainSelectorActivity"),
            Arrays.asList("android.net.Uri.Builder", "query"),
            Arrays.asList("android.net.Uri", "withAppendedPath"),
            Arrays.asList("android.security.KeyChain", "createInstallIntent"),
            Arrays.asList("android.content.Intent", "putExtra"),
            Arrays.asList("android.net.Uri.Builder", "fragment"),
            Arrays.asList("android.speech.RecognizerIntent", "getVoiceDetailsIntent"),
            Arrays.asList("android.net.VpnService", "prepare"),
            Arrays.asList("android.content.Intent", "makeRestartActivityTask")
    );

    public static List<List<String>> iccRespondingCallbacks = Arrays.asList(
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onSystemUpdatePending"),
            Arrays.asList("android.app.Service", "onRebind"),
            Arrays.asList("android.widget.ShareActionProvider$OnShareTargetSelectedListener", "onShareTargetSelected"),
            Arrays.asList("android.app.Service", "onUnbind"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onPasswordFailed"),
            Arrays.asList("android.app.Service", "onBind"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onSecurityLogsAvailable"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onDisableRequested"),
            Arrays.asList("android.app.IntentService", "onHandleIntent"),
            Arrays.asList("android.content.IntentSender$OnFinished", "onSendFinished"),
            Arrays.asList("android.app.Service", "onStartCommand"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onLockTaskModeExiting"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onPasswordExpiring"),
            Arrays.asList("android.app.Fragment", "onActivityResult"),
            Arrays.asList("android.preference.RingtonePreference", "onPrepareRingtonePickerIntent"),
            Arrays.asList("android.media.session.MediaSession$Callback", "onMediaButtonEvent"),
            Arrays.asList("android.preference.PreferenceFragment", "onActivityResult"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onDisabled"),
            Arrays.asList("android.app.Activity", "onActivityResult"),
            Arrays.asList("android.app.FragmentHostCallback", "onStartIntentSenderFromFragment"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onNetworkLogsAvailable"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onLockTaskModeEntering"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onChoosePrivateKeyAlias"),
            Arrays.asList("android.app.Service", "onStart"),
            Arrays.asList("android.content.ContentProvider", "insert"),
            Arrays.asList("android.content.ContentProvider", "delete"),
            Arrays.asList("android.preference.PreferenceManager$OnActivityResultListener", "onActivityResult"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onReadyForUserInitialization"),
            Arrays.asList("android.content.ContentProvider", "query"),
            Arrays.asList("android.service.voice.VoiceInteractionSession", "onTaskStarted"),
            Arrays.asList("android.app.Activity", "onNewIntent"),
            Arrays.asList("android.app.Activity", "navigateUpToFromChild"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onProfileProvisioningComplete"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onPasswordChanged"),
            Arrays.asList("android.content.ContentProvider", "getType"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onBugreportShared"),
            Arrays.asList("android.app.FragmentHostCallback", "onStartActivityFromFragment"),
            Arrays.asList("android.content.BroadcastReceiver", "onReceive"),
            Arrays.asList("android.content.ContentProvider", "update"),
            Arrays.asList("android.app.Activity", "onActivityReenter"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onPasswordSucceeded"),
            Arrays.asList("android.preference.RingtonePreference", "onActivityResult"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onBugreportFailed"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onEnabled"),
            Arrays.asList("android.app.PendingIntent$OnFinished", "onSendFinished"),
            Arrays.asList("android.app.Service", "onTaskRemoved"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onUserAdded"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onBugreportSharingDeclined"),
            Arrays.asList("android.app.admin.DeviceAdminReceiver", "onUserRemoved"),
            Arrays.asList("android.content.ContentProvider", "bulkInsert")
    );
    public static List<List<String>> iccRespondingApis = Arrays.asList(
            Arrays.asList("android.content.IntentFilter", "addAction"),
            Arrays.asList("android.content.IntentFilter", "addDataAuthority"),
            Arrays.asList("android.content.IntentFilter", "create"),
            Arrays.asList("android.app.Notification$CarExtender$UnreadConversation", "getReadPendingIntent"),
            Arrays.asList("android.content.pm.ShortcutInfo", "getIntent"),
            Arrays.asList("android.app.Activity", "getIntent"),
            Arrays.asList("android.content.IntentFilter", "addDataType"),
            Arrays.asList("android.content.IntentFilter", "addCategory"),
            Arrays.asList("android.content.IntentFilter", "<init>"),
            Arrays.asList("android.app.RemoteAction", "getActionIntent"),
            Arrays.asList("android.app.Notification$WearableExtender", "getDisplayIntent"),
            Arrays.asList("android.app.Activity", "setResult"),
            Arrays.asList("android.app.Activity", "getParentActivityIntent"),
            Arrays.asList("android.content.ContentProviderResult", "<init>"),
            Arrays.asList("android.content.IntentFilter", "addDataSchemeSpecificPart"),
            Arrays.asList("android.content.IntentFilter", "addDataPath"),
            Arrays.asList("android.content.IntentFilter", "addDataScheme"),
            Arrays.asList("android.app.Notification$CarExtender$UnreadConversation", "getReplyPendingIntent")
    );
    public static List<List<String>> iccActivitingApis = Arrays.asList(
            Arrays.asList("android.content.Context", "sendOrderedBroadcastAsUser"),
            Arrays.asList("android.telephony.TelephonyManager", "sendVisualVoicemailSms"),
            Arrays.asList("android.app.AlarmManager", "cancel"),
            Arrays.asList("android.location.LocationManager", "removeProximityAlert"),
            Arrays.asList("android.content.Context", "removeStickyBroadcast"),
            Arrays.asList("android.content.Context", "sendStickyOrderedBroadcastAsUser"),
            Arrays.asList("android.app.Notification$CarExtender$Builder", "setReplyAction"),
            Arrays.asList("android.content.Context", "sendBroadcastWithMultiplePermissions"),
            Arrays.asList("android.content.Context", "sendBroadcast"),
            Arrays.asList("android.content.Context", "removeStickyBroadcastAsUser"),
            Arrays.asList("android.app.AlarmManager", "setRepeating"),
            Arrays.asList("android.content.IntentSender", "sendIntent"),
            Arrays.asList("android.content.Context", "revokeUriPermission"),
            Arrays.asList("android.content.ContentResolver", "insert"),
            Arrays.asList("android.content.ContentResolver", "openOutputStream"),
            Arrays.asList("android.app.Activity", "startActivityIfNeeded"),
            Arrays.asList("android.content.ContentResolver", "openTypedAssetFileDescriptor"),
            Arrays.asList("android.location.LocationManager", "removeUpdates"),
            Arrays.asList("android.app.Activity", "startActivityFromFragment"),
            Arrays.asList("android.bluetooth.le.BluetoothLeScanner", "stopScan"),
            Arrays.asList("android.content.ContentResolver", "query"),
            Arrays.asList("android.net.sip.SipManager", "open"),
            Arrays.asList("android.content.ContentResolver", "openInputStream"),
            Arrays.asList("android.nfc.NfcAdapter", "enableForegroundDispatch"),
            Arrays.asList("android.content.Context", "sendStickyBroadcast"),
            Arrays.asList("android.telephony.SmsManager", "createAppSpecificSmsToken"),
            Arrays.asList("android.content.ContentResolver", "call"),
            Arrays.asList("android.content.Context", "sendOrderedBroadcast"),
            Arrays.asList("android.app.AlarmManager", "setInexactRepeating"),
            Arrays.asList("android.content.Context", "stopService"),
            Arrays.asList("android.media.session.MediaSession", "setSessionActivity"),
            Arrays.asList("android.service.voice.VoiceInteractionSession", "startAssistantActivity"),
            Arrays.asList("android.content.Context", "sendStickyOrderedBroadcast"),
            Arrays.asList("android.content.ContentResolver", "bulkInsert"),
            Arrays.asList("android.appwidget.AppWidgetManager", "requestPinAppWidget"),
            Arrays.asList("android.media.AudioManager", "registerMediaButtonEventReceiver"),
            Arrays.asList("android.media.AudioManager", "unregisterMediaButtonEventReceiver"),
            Arrays.asList("android.telephony.gsm.SmsManager", "sendTextMessage"),
            Arrays.asList("android.location.LocationManager", "requestLocationUpdates"),
            Arrays.asList("android.hardware.usb.UsbManager", "requestPermission"),
            Arrays.asList("android.app.Notification$Builder", "addAction"),
            Arrays.asList("android.location.LocationManager", "addProximityAlert"),
            Arrays.asList("android.content.Context", "bindIsolatedService"),
            Arrays.asList("android.app.PendingIntent", "send"),
            Arrays.asList("android.app.Notification$Builder", "setContentIntent"),
            Arrays.asList("android.app.Activity", "navigateUpTo"),
            Arrays.asList("android.app.Activity", "startIntentSender"),
            Arrays.asList("android.app.AlarmManager", "set"),
            Arrays.asList("android.net.ConnectivityManager", "registerNetworkCallback"),
            Arrays.asList("android.net.VpnService$Builder", "setConfigureIntent"),
            Arrays.asList("android.content.Context", "startActivities"),
            Arrays.asList("android.app.Notification$Action", "<init>"),
            Arrays.asList("android.app.AlarmManager", "setAlarmClock"),
            Arrays.asList("android.telephony.SmsManager", "sendDataMessage"),
            Arrays.asList("android.content.Context", "bindServiceAsUser"),
            Arrays.asList("android.telephony.SmsManager", "downloadMultimediaMessage"),
            Arrays.asList("android.app.Notification$Builder", "setDeleteIntent"),
            Arrays.asList("android.telephony.SmsManager", "injectSmsPdu"),
            Arrays.asList("android.app.admin.DevicePolicyManager", "enableSystemApp"),
            Arrays.asList("android.net.ConnectivityManager", "unregisterNetworkCallback"),
            Arrays.asList("android.content.ContentResolver", "delete"),
            Arrays.asList("android.telephony.SmsManager", "sendMultimediaMessage"),
            Arrays.asList("android.content.ContentResolver", "update"),
            Arrays.asList("android.app.Activity", "startActivities"),
            Arrays.asList("android.app.LocalActivityManager", "startActivity"),
            Arrays.asList("android.app.Activity", "startActivity"),
            Arrays.asList("android.widget.RemoteViews", "setOnClickFillInIntent"),
            Arrays.asList("android.app.AlarmManager", "setExactAndAllowWhileIdle"),
            Arrays.asList("android.content.Context", "sendStickyBroadcastAsUser"),
            Arrays.asList("android.net.ConnectivityManager", "releaseNetworkRequest"),
            Arrays.asList("android.app.Notification$CarExtender$Builder", "setReadPendingIntent"),
            Arrays.asList("android.app.Fragment", "startActivity"),
            Arrays.asList("android.service.voice.VoiceInteractionSession", "startVoiceActivity"),
            Arrays.asList("android.content.Context", "startIntentSender"),
            Arrays.asList("android.media.session.MediaSession", "setMediaButtonReceiver"),
            Arrays.asList("android.content.Context", "sendBroadcastAsUser"),
            Arrays.asList("android.service.quicksettings.TileService", "startActivityAndCollapse"),
            Arrays.asList("android.app.Fragment", "startActivityForResult"),
            Arrays.asList("android.app.AlarmManager", "setExact"),
            Arrays.asList("android.content.ContentResolver", "acquireContentProviderClient"),
            Arrays.asList("android.content.Context", "unbindService"),
            Arrays.asList("android.content.Context", "unregisterReceiver"),
            Arrays.asList("android.content.Context", "registerReceiver"),
            Arrays.asList("android.content.Context", "startActivity"),
            Arrays.asList("android.content.ContentResolver", "acquireUnstableContentProviderClient"),
            Arrays.asList("android.bluetooth.le.BluetoothLeScanner", "startScan"),
            Arrays.asList("android.app.Activity", "startActivityFromChild"),
            Arrays.asList("android.app.AlarmManager", "setWindow"),
            Arrays.asList("android.app.Notification$Builder", "setFullScreenIntent"),
            Arrays.asList("android.app.Activity", "startIntentSenderForResult"),
            Arrays.asList("android.net.ConnectivityManager", "requestNetwork"),
            Arrays.asList("android.content.Context", "startService"),
            Arrays.asList("android.app.Notification$Action$Builder", "<init>"),
            Arrays.asList("android.content.ContentResolver", "openFileDescriptor"),
            Arrays.asList("android.location.LocationManager", "requestSingleUpdate"),
            Arrays.asList("android.app.Notification$WearableExtender", "setDisplayIntent"),
            Arrays.asList("android.app.Activity", "startNextMatchingActivity"),
            Arrays.asList("android.telephony.SmsManager", "sendTextMessage"),
            Arrays.asList("android.content.Context", "startForegroundService"),
            Arrays.asList("android.print.PrinterInfo$Builder", "setInfoIntent"),
            Arrays.asList("android.app.Activity", "startActivityForResult"),
            Arrays.asList("android.content.BroadcastReceiver", "peekService"),
            Arrays.asList("android.app.AlarmManager", "setAndAllowWhileIdle"),
            Arrays.asList("android.widget.RemoteViews", "setOnClickPendingIntent"),
            Arrays.asList("android.content.Context", "bindService"),
            Arrays.asList("android.app.Fragment", "startIntentSenderForResult"),
            Arrays.asList("android.telephony.gsm.SmsManager", "sendDataMessage"),
            Arrays.asList("android.app.ActivityManager$AppTask", "startActivity"),
            Arrays.asList("android.app.Activity", "startIntentSenderFromChild"),
            Arrays.asList("android.content.ContentResolver", "openAssetFileDescriptor")
    );
    public static List<List<String>> iccRetrievingApis = Arrays.asList(
            Arrays.asList("android.content.Intent", "toString"),
            Arrays.asList("android.content.Intent", "getIntentOld"),
            Arrays.asList("android.content.Intent", "getType"),
            Arrays.asList("android.content.Intent", "getLongArrayExtra"),
            Arrays.asList("android.content.Intent", "getSerializableExtra"),
            Arrays.asList("android.content.Intent", "getFlags"),
            Arrays.asList("android.content.Intent", "resolveTypeIfNeeded"),
            Arrays.asList("android.content.Intent", "getIntArrayExtra"),
            Arrays.asList("android.content.Intent", "getCharSequenceExtra"),
            Arrays.asList("android.content.Intent", "getCharArrayExtra"),
            Arrays.asList("android.content.Intent", "getByteExtra"),
            Arrays.asList("android.content.Intent", "getDoubleArrayExtra"),
            Arrays.asList("android.content.Intent", "getFloatArrayExtra"),
            Arrays.asList("android.content.Intent", "getComponent"),
            Arrays.asList("android.content.Intent", "getSourceBounds"),
            Arrays.asList("android.content.Intent", "toURI"),
            Arrays.asList("android.content.Intent", "getLongExtra"),
            Arrays.asList("android.content.Intent", "getStringArrayExtra"),
            Arrays.asList("android.content.Intent", "getBooleanExtra"),
            Arrays.asList("android.content.Intent", "getParcelableArrayListExtra"),
            Arrays.asList("android.content.Intent", "getData"),
            Arrays.asList("android.content.Intent", "getDataString"),
            Arrays.asList("android.content.Intent", "getParcelableArrayExtra"),
            Arrays.asList("android.content.Intent", "getCharSequenceArrayExtra"),
            Arrays.asList("android.content.Intent", "getBooleanArrayExtra"),
            Arrays.asList("android.content.Intent", "getPackage"),
            Arrays.asList("android.content.Intent", "getShortArrayExtra"),
            Arrays.asList("android.content.Intent", "getStringExtra"),
            Arrays.asList("android.content.Intent", "getParcelableExtra"),
            Arrays.asList("android.content.Intent", "getClipData"),
            Arrays.asList("android.content.Intent", "hasFileDescriptors"),
            Arrays.asList("android.content.Intent", "getScheme"),
            Arrays.asList("android.content.Intent", "resolveType"),
            Arrays.asList("android.content.Intent", "getIntExtra"),
            Arrays.asList("android.content.Intent", "getDoubleExtra"),
            Arrays.asList("android.content.Intent", "getBundleExtra"),
            Arrays.asList("android.content.Intent", "getCharExtra"),
            Arrays.asList("android.content.Intent", "getExtras"),
            Arrays.asList("android.content.Intent", "toUri"),
            Arrays.asList("android.content.Intent", "getAction"),
            Arrays.asList("android.content.Intent", "getCharSequenceArrayListExtra"),
            Arrays.asList("android.content.Intent", "getShortExtra"),
            Arrays.asList("android.content.Intent", "getSelector"),
            Arrays.asList("android.content.Intent", "getFloatExtra"),
            Arrays.asList("android.content.Intent", "getByteArrayExtra"),
            Arrays.asList("android.content.Intent", "describeContents"),
            Arrays.asList("android.content.Intent", "getIntegerArrayListExtra"),
            Arrays.asList("android.content.Intent", "getCategories"),
            Arrays.asList("android.content.Intent", "getStringArrayListExtra"),
            Arrays.asList("android.content.IntentFilter", "typesIterator"),
            Arrays.asList("android.app.PendingIntent", "describeContents"),
            Arrays.asList("android.content.IntentFilter", "getAction"),
            Arrays.asList("android.content.IntentFilter", "getDataScheme"),
            Arrays.asList("android.app.PendingIntent", "getCreatorUid"),
            Arrays.asList("android.content.IntentSender", "toString"),
            Arrays.asList("android.content.IntentFilter", "getDataPath"),
            Arrays.asList("android.app.RemoteInput", "getResultsFromIntent"),
            Arrays.asList("android.content.IntentFilter", "schemeSpecificPartsIterator"),
            Arrays.asList("android.content.IntentFilter", "categoriesIterator"),
            Arrays.asList("android.content.IntentFilter", "actionsIterator"),
            Arrays.asList("android.app.PendingIntent", "toString"),
            Arrays.asList("android.content.IntentFilter", "getCategory"),
            Arrays.asList("android.content.IntentFilter", "pathsIterator"),
            Arrays.asList("android.app.PendingIntent", "getTargetPackage"),
            Arrays.asList("android.content.IntentSender", "describeContents"),
            Arrays.asList("android.content.IntentFilter", "countDataSchemeSpecificParts"),
            Arrays.asList("android.app.PendingIntent", "getCreatorPackage"),
            Arrays.asList("android.content.IntentFilter", "getPriority"),
            Arrays.asList("android.content.IntentFilter", "dump"),
            Arrays.asList("android.content.ContentResolver", "getStreamTypes"),
            Arrays.asList("android.content.IntentFilter", "getDataSchemeSpecificPart"),
            Arrays.asList("android.content.IntentFilter", "authoritiesIterator"),
            Arrays.asList("android.app.PendingIntent", "getIntentSender"),
            Arrays.asList("android.content.IntentSender", "getCreatorUid"),
            Arrays.asList("android.content.IntentSender", "getCreatorUserHandle"),
            Arrays.asList("android.content.IntentFilter", "countDataSchemes"),
            Arrays.asList("android.content.IntentFilter", "countActions"),
            Arrays.asList("android.content.IntentFilter", "countDataTypes"),
            Arrays.asList("android.app.PendingIntent", "writePendingIntentOrNullToParcel"),
            Arrays.asList("android.content.IntentFilter", "describeContents"),
            Arrays.asList("android.content.IntentFilter", "getDataAuthority"),
            Arrays.asList("android.content.IntentSender", "getCreatorPackage"),
            Arrays.asList("android.webkit.WebChromeClient$FileChooserParams", "parseResult"),
            Arrays.asList("android.app.RemoteInput", "getDataResultsFromIntent"),
            Arrays.asList("android.content.IntentFilter", "countDataAuthorities"),
            Arrays.asList("android.content.IntentFilter", "schemesIterator"),
            Arrays.asList("android.app.PendingIntent", "getCreatorUserHandle"),
            Arrays.asList("android.content.IntentFilter", "countDataPaths"),
            Arrays.asList("android.content.IntentFilter", "getDataType"),
            Arrays.asList("android.content.IntentFilter", "countCategories"),
            Arrays.asList("android.app.PendingIntent", "writeToParcel"),
            Arrays.asList("android.content.ContentResolver", "getType")
    );

    /**
     * Format: [[className, methodName, Parameter1, Parameter2, ...]]
     */
    public static List<List<String>> ICCRelatedAPIs = Stream.of(iccActivitingApis, iccConstructingApis, iccRespondingApis, iccResolvingApis, iccUncertainApis, iccRetrievingApis, iccOtherApis)
            .flatMap(Collection::stream)
            .collect(Collectors.toList());

    public static List<String> ICCObjectCls = Arrays.asList("android.content.Intent", "android.net.Uri", "android.app.PendingIntent","android.content.ContentValues");
    public static List<String> callbackMtds = Arrays.asList("onCreate", "onStart", "onResume", "onPause", "onStop", "onDestroy");
}
