package usc.edu.sql.fpa.utils;

import java.util.Arrays;
import java.util.List;

public class MethodConstants {

	public static List<String> contentResolverAPIs = Arrays.asList("query", "insert", "delete");
	public static List<String> Service_Senders = Arrays.asList(
			"android.content.ComponentName startService(android.content.Intent)",
			"boolean bindService(android.content.Intent,android.content.ServiceConnection,int)",
			"boolean bindIsolatedService(android.content.Intent,int,String,java.util.concurrent.Executor,android.content.ServiceConnection)");

	public static List<String> BroadcastReceiver_Senders = Arrays.asList(
			"android.os.IBinder peekService(android.content.Context,android.content.Intent)",
			"void sendBroadcast(android.content.Intent)", "void sendBroadcast(android.content.Intent,java.lang.String)",
			"void sendOrderedBroadcast(android.content.Intent,java.lang.String)",
			"void sendOrderedBroadcast(android.content.Intent,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
			"void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String)",
			"void sendOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void sendStickyBroadcast(android.content.Intent)",
			"void sendStickyOrderedBroadcast(android.content.Intent,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void sendStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
			"void sendStickyOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void removeStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)");

	public static List<String> Activity_Senders = Arrays.asList("void setResult(int,android.content.Intent)",
			"void setResult(int)", "void startActivityForResult(android.content.Intent,int)",
			"void startActivityForResult(android.content.Intent,int,android.os.Bundle)",
			"void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int)",
			"void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)",
			"void startActivity(android.content.Intent)",
			"void startActivity(android.content.Intent,android.os.Bundle)",
			"void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int)",
			"void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int,android.os.Bundle)",
			"boolean startActivityIfNeeded(android.content.Intent,int)",
			"boolean startActivityIfNeeded(android.content.Intent,int,android.os.Bundle)",
			"boolean startNextMatchingActivity(android.content.Intent)",
			"boolean startNextMatchingActivity(android.content.Intent,android.os.Bundle)");

	public static List<String> Service_Recievers = Arrays.asList("void onStart(android.content.Intent,int)",
			"int onStartCommand(android.content.Intent,int,int)", "android.os.IBinder onBind(android.content.Intent)",
			"void onHandleIntent(android.content.Intent)", "boolean onUnbind(android.content.Intent)",
			"void onRebind(android.content.Intent)");

	public static List<String> Activity_Recievers_APIs = Arrays.asList("android.content.Intent getIntent()",
			"void setResult(int,android.content.Intent)", "void setResult(int)",
			"android.content.Intent getParentActivityIntent()");

	public static List<String> Activity_Recievers_Callbacks = Arrays.asList("void onNewIntent(android.content.Intent)",
			"void onActivityResult(int,int,android.content.Intent)", "void onCreate(android.os.Bundle)");

	public static List<String> BroadCastReceiver_Recievers = Arrays
			.asList("void onReceive(android.content.Context,android.content.Intent)");

	public static List<String> iccCalls = Arrays.asList("void setIntent(android.content.Intent)",
			"android.content.Intent getIntent()", "void startActivityForResult(android.content.Intent,int)",
			"void startActivityForResult(android.content.Intent,int,android.os.Bundle)",
			"void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int)",
			"void startIntentSenderForResult(android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)",
			"void startActivity(android.content.Intent)",

			"void startActivity(android.content.Intent,android.os.Bundle)",
			"void startActivities(android.content.Intent[])",
			"void startActivities(android.content.Intent[],android.os.Bundle)",
			"void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int)",
			"void startIntentSender(android.content.IntentSender,android.content.Intent,int,int,int,android.os.Bundle)",
			"boolean startActivityIfNeeded(android.content.Intent,int)",
			"boolean startActivityIfNeeded(android.content.Intent,int,android.os.Bundle)",
			"boolean startNextMatchingActivity(android.content.Intent)",
			"boolean startNextMatchingActivity(android.content.Intent,android.os.Bundle)",
			"void startActivityFromChild(android.app.Activity,android.content.Intent,int)",
			"void startActivityFromChild(android.app.Activity,android.content.Intent,int,android.os.Bundle)",
			"void startActivityFromFragment(android.app.Fragment,android.content.Intent,int)",
			"void startActivityFromFragment(android.app.Fragment,android.content.Intent,int,android.os.Bundle)",
			"void startIntentSenderFromChild(android.app.Activity,android.content.IntentSender,int,android.content.Intent,int,int,int)",
			"void startIntentSenderFromChild(android.app.Activity,android.content.IntentSender,int,android.content.Intent,int,int,int,android.os.Bundle)",
			"void sendBroadcast(android.content.Intent)", "void sendBroadcast(android.content.Intent,java.lang.String)",
			"void sendOrderedBroadcast(android.content.Intent,java.lang.String)",
			"void sendOrderedBroadcast(android.content.Intent,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
			"void sendBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String)",
			"void sendOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,java.lang.String,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void sendStickyBroadcast(android.content.Intent)",
			"void sendStickyOrderedBroadcast(android.content.Intent,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void removeStickyBroadcast(android.content.Intent)",
			"void sendStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
			"void sendStickyOrderedBroadcastAsUser(android.content.Intent,android.os.UserHandle,android.content.BroadcastReceiver,android.os.Handler,int,java.lang.String,android.os.Bundle)",
			"void removeStickyBroadcastAsUser(android.content.Intent,android.os.UserHandle)",
			"android.content.Intent registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter)",
			"android.content.Intent registerReceiver(android.content.BroadcastReceiver,android.content.IntentFilter,java.lang.String,android.os.Handler)",
			"void unregisterReceiver(android.content.BroadcastReceiver)",
			"android.content.ComponentName startService(android.content.Intent)",
			"boolean stopService(android.content.Intent)",
			"boolean bindService(android.content.Intent,android.content.ServiceConnection,int)",
			"void unbindService(android.content.ServiceConnection)");

	public static List<String> intentAPIs = Arrays.asList("void <init>()", "void <init>(android.content.Intent)",
			"void <init>(java.lang.String)", "void <init>(java.lang.String,android.net.Uri)",
			"void <init>(android.content.Context,java.lang.Class)",
			"void <init>(java.lang.String,android.net.Uri,android.content.Context,java.lang.Class)",
			"android.content.Intent createChooser(android.content.Intent,java.lang.CharSequence)",
			"java.lang.Object clone()", "android.content.Intent cloneFilter()",
			"android.content.Intent makeMainActivity(android.content.ComponentName)",
			"android.content.Intent makeMainSelectorActivity(java.lang.String,java.lang.String)",
			"android.content.Intent makeRestartActivityTask(android.content.ComponentName)",
			"android.content.Intent getIntent(java.lang.String)",
			"android.content.Intent parseUri(java.lang.String,int)",
			"android.content.Intent getIntentOld(java.lang.String)", "java.lang.String getAction()",
			"android.net.Uri getData()", "java.lang.String getDataString()", "java.lang.String getScheme()",
			"java.lang.String getType()", "java.lang.String resolveType(android.content.Context)",
			"java.lang.String resolveType(android.content.ContentResolver)",
			"java.lang.String resolveTypeIfNeeded(android.content.ContentResolver)",
			"boolean hasCategory(java.lang.String)", "java.util.Set getCategories()",
			"android.content.Intent getSelector()", "android.content.ClipData getClipData()",
			"void setExtrasClassLoader(java.lang.ClassLoader)", "boolean hasExtra(java.lang.String)",
			"boolean hasFileDescriptors()", "boolean getBooleanExtra(java.lang.String,boolean)",
			"byte getByteExtra(java.lang.String,byte)", "short getShortExtra(java.lang.String,short)",
			"char getCharExtra(java.lang.String,char)", "int getIntExtra(java.lang.String,int)",
			"long getLongExtra(java.lang.String,long)", "float getFloatExtra(java.lang.String,float)",
			"double getDoubleExtra(java.lang.String,double)", "java.lang.String getStringExtra(java.lang.String)",
			"java.lang.CharSequence getCharSequenceExtra(java.lang.String)",
			"android.os.Parcelable getParcelableExtra(java.lang.String)",
			"android.os.Parcelable[] getParcelableArrayExtra(java.lang.String)",
			"java.util.ArrayList getParcelableArrayListExtra(java.lang.String)",
			"java.io.Serializable getSerializableExtra(java.lang.String)",
			"java.util.ArrayList getIntegerArrayListExtra(java.lang.String)",
			"java.util.ArrayList getStringArrayListExtra(java.lang.String)",
			"java.util.ArrayList getCharSequenceArrayListExtra(java.lang.String)",
			"boolean[] getBooleanArrayExtra(java.lang.String)", "byte[] getByteArrayExtra(java.lang.String)",
			"short[] getShortArrayExtra(java.lang.String)", "char[] getCharArrayExtra(java.lang.String)",
			"int[] getIntArrayExtra(java.lang.String)", "long[] getLongArrayExtra(java.lang.String)",
			"float[] getFloatArrayExtra(java.lang.String)", "double[] getDoubleArrayExtra(java.lang.String)",
			"java.lang.String[] getStringArrayExtra(java.lang.String)",
			"java.lang.CharSequence[] getCharSequenceArrayExtra(java.lang.String)",
			"android.os.Bundle getBundleExtra(java.lang.String)", "android.os.Bundle getExtras()", "int getFlags()",
			"java.lang.String getPackage()", "android.content.ComponentName getComponent()",
			"android.graphics.Rect getSourceBounds()",
			"android.content.ComponentName resolveActivity(android.content.pm.PackageManager)",
			"android.content.pm.ActivityInfo resolveActivityInfo(android.content.pm.PackageManager,int)",
			"android.content.Intent setAction(java.lang.String)", "android.content.Intent setData(android.net.Uri)",
			"android.content.Intent setDataAndNormalize(android.net.Uri)",
			"android.content.Intent setType(java.lang.String)",
			"android.content.Intent setTypeAndNormalize(java.lang.String)",
			"android.content.Intent setDataAndType(android.net.Uri,java.lang.String)",
			"android.content.Intent setDataAndTypeAndNormalize(android.net.Uri,java.lang.String)",
			"android.content.Intent addCategory(java.lang.String)", "void removeCategory(java.lang.String)",
			"void setSelector(android.content.Intent)", "void setClipData(android.content.ClipData)",
			"android.content.Intent putExtra(java.lang.String,boolean)",
			"android.content.Intent putExtra(java.lang.String,byte)",
			"android.content.Intent putExtra(java.lang.String,char)",
			"android.content.Intent putExtra(java.lang.String,short)",
			"android.content.Intent putExtra(java.lang.String,int)",
			"android.content.Intent putExtra(java.lang.String,long)",
			"android.content.Intent putExtra(java.lang.String,float)",
			"android.content.Intent putExtra(java.lang.String,double)",
			"android.content.Intent putExtra(java.lang.String,java.lang.String)",
			"android.content.Intent putExtra(java.lang.String,java.lang.CharSequence)",
			"android.content.Intent putExtra(java.lang.String,android.os.Parcelable)",
			"android.content.Intent putExtra(java.lang.String,android.os.Parcelable[])",
			"android.content.Intent putParcelableArrayListExtra(java.lang.String,java.util.ArrayList)",
			"android.content.Intent putIntegerArrayListExtra(java.lang.String,java.util.ArrayList)",
			"android.content.Intent putStringArrayListExtra(java.lang.String,java.util.ArrayList)",
			"android.content.Intent putCharSequenceArrayListExtra(java.lang.String,java.util.ArrayList)",
			"android.content.Intent putExtra(java.lang.String,java.io.Serializable)",
			"android.content.Intent putExtra(java.lang.String,boolean[])",
			"android.content.Intent putExtra(java.lang.String,byte[])",
			"android.content.Intent putExtra(java.lang.String,short[])",
			"android.content.Intent putExtra(java.lang.String,char[])",
			"android.content.Intent putExtra(java.lang.String,int[])",
			"android.content.Intent putExtra(java.lang.String,long[])",
			"android.content.Intent putExtra(java.lang.String,float[])",
			"android.content.Intent putExtra(java.lang.String,double[])",
			"android.content.Intent putExtra(java.lang.String,java.lang.String[])",
			"android.content.Intent putExtra(java.lang.String,java.lang.CharSequence[])",
			"android.content.Intent putExtra(java.lang.String,android.os.Bundle)",
			"android.content.Intent putExtras(android.content.Intent)",
			"android.content.Intent putExtras(android.os.Bundle)",
			"android.content.Intent replaceExtras(android.content.Intent)",
			"android.content.Intent replaceExtras(android.os.Bundle)", "void removeExtra(java.lang.String)",
			"android.content.Intent setFlags(int)", "android.content.Intent addFlags(int)",
			"android.content.Intent setPackage(java.lang.String)",
			"android.content.Intent setComponent(android.content.ComponentName)",
			"android.content.Intent setClassName(android.content.Context,java.lang.String)",
			"android.content.Intent setClassName(java.lang.String,java.lang.String)",
			"android.content.Intent setClass(android.content.Context,java.lang.Class)",
			"void setSourceBounds(android.graphics.Rect)", "int fillIn(android.content.Intent,int)",
			"boolean filterEquals(android.content.Intent)", "int filterHashCode()", "java.lang.String toString()",
			"java.lang.String toURI()", "java.lang.String toUri(int)", "int describeContents()",
			"void writeToParcel(android.os.Parcel,int)", "void readFromParcel(android.os.Parcel)",
			"android.content.Intent parseIntent(android.content.res.Resources,org.xmlpull.v1.XmlPullParser,android.util.AttributeSet)",
			"java.lang.String normalizeMimeType(java.lang.String)", "void <clinit>()");

}
